databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_campaign_targets.CATALOGNAME=Marketing_Insights_DS
databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_campaign_targets.SCHEMANAME=dbo
