databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_customer_demographics.CATALOGNAME=marketing_insights
databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_customer_demographics.SCHEMANAME=dbo
