databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_semantic_template.CATALOGNAME=marketing_insights
databases.marketing_insights.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_semantic_template.SCHEMANAME=dbo
